---
- name: Perform site health check
  hosts: "{{ _host }}"
  gather_facts: false
  become: true

  vars:
    sites: "{{ ssl_target_sites_list.split(',') }}"

  tasks:
    - name: GET site url and validate certificate
      loop: "{{ sites }}"
      loop_control:
        loop_var: site
      ansible.builtin.uri:
        url: "https://{{ site }}"
        method: GET
        validate_certs: true
