---
- name: Restore site ssl artifacts from backups
  hosts: "{{ _host }}"
  gather_facts: false
  become: true

  vars:
    sites: "{{ ssl_target_sites_list.split(',') }}"

  tasks:
    - name: Restore site ssl artifacts
      loop: "{{ sites }}"
      loop_control:
        loop_var: site
      ansible.builtin.include_tasks: tasks/site_ssl_restore.yml

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
