---
- name: Cleanup site ssl backups
  hosts: "{{ _host }}"
  gather_facts: false
  become: true

  vars:
    sites: "{{ ssl_target_sites_list.split(',') }}"

  tasks:
    - name: Cleanup site ssl backups
      loop: "{{ sites }}"
      loop_control:
        loop_var: site
      ansible.builtin.include_tasks: tasks/site_ssl_cleanup.yml
