---
- name: Restore site ssl cert
  notify: Restart nginx
  ansible.builtin.copy:
    remote_src: true
    dest: "{{ letsencrypt_dir }}/certs/fullchain_{{ site }}.pem"
    src: "{{ letsencrypt_dir }}/backup/certs/fullchain_{{ site }}.pem.bak"

- name: Restore site ssl key
  notify: Restart nginx
  ansible.builtin.copy:
    remote_src: true
    dest: "{{ letsencrypt_dir }}/keys/{{ site }}.key"
    src: "{{ letsencrypt_dir }}/backup/keys/{{ site }}.key.bak"

- name: Restore site ssl csr
  notify: Restart nginx
  ansible.builtin.copy:
    remote_src: true
    dest: "{{ letsencrypt_dir }}/csrs/{{ site }}.csr"
    src: "{{ letsencrypt_dir }}/backup/csrs/{{ site }}.csr.bak"
