---
- name: Backup site ssl cert
  ansible.builtin.copy:
    remote_src: true
    src: "{{ letsencrypt_dir }}/certs/fullchain_{{ site }}.pem"
    dest: "{{ letsencrypt_dir }}/backup/certs/fullchain_{{ site }}.pem.bak"

- name: Backup site ssl key
  ansible.builtin.copy:
    remote_src: true
    src: "{{ letsencrypt_dir }}/keys/{{ site }}.key"
    dest: "{{ letsencrypt_dir }}/backup/keys/{{ site }}.key.bak"

- name: Backup site ssl csr
  ansible.builtin.copy:
    remote_src: true
    src: "{{ letsencrypt_dir }}/csrs/{{ site }}.csr"
    dest: "{{ letsencrypt_dir }}/backup/csrs/{{ site }}.csr.bak"
