---
- name: Generate Let's Encrypt account key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_account_key }}"

- name: Remove existing ssl files
  loop:
    - "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"
    - "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    - "{{ letsencrypt_certs_dir }}/{{ domain_name }}.pem"
    - "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Generate Let's Encrypt private key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"
    mode: "{{ letsencrypt_keys_mode | default(omit) }}"

- name: Generate Let's Encrypt CSR
  community.crypto.openssl_csr:
    path: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    privatekey_path: "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"
    common_name: "{{ domain_name }}"

- name: Begin Let's Encrypt challenges
  register: r_acme_challenge
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    terms_agreed: 1
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem"
    remaining_days: 91

- name: "Implement challenge | {{ acme_challenge_type }}"
  ansible.builtin.include_tasks:
    file: "{{ acme_challenge_type }}.yml" 

- name: Complete Let's Encrypt challenges
  notify: Restart nginx
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.pem"
    chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem"
    data: "{{ r_acme_challenge }}"

- name: Configure nginx
  when: acme_configure_nginx
  ansible.builtin.include_tasks: nginx.yml
