---
- name: Check if cert exists
  register: r_crt_check
  ansible.builtin.stat:
    path: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem"

- name: Check validity of existing cert
  when: r_crt_check.stat.exists
  register: r_crt_info
  community.crypto.x509_certificate_info:
    path: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem"
    valid_at:
      custom_expiry: "{{ acme_custom_expiry }}"

- name: "Generate cert for {{ domain_name }}"
  when: not r_crt_check.stat.exists or not r_crt_info.valid_at.custom_expiry|default(false)
  include_tasks: generate_crt.yml