---
- name: Check if nginx site exists
  register: r_nginx_site_check
  ansible.builtin.stat:
    path: "/etc/nginx/sites-available/{{ domain_name }}.conf"

- name: "Update nginx ssl cert | {{ domain_name }}"
  when: r_nginx_site_check.stat.exists
  notify: Restart nginx
  ansible.builtin.lineinfile:
    path: "/etc/nginx/sites-available/{{ domain_name }}.conf"
    regexp: "^(.*)ssl_certificate {{ letsencrypt_dir }}"
    line: "\tssl_certificate {{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.pem;"

- name: "Update nginx ssl key | {{ domain_name }}"
  when: r_nginx_site_check.stat.exists
  notify: Restart nginx
  ansible.builtin.lineinfile:
    path: "/etc/nginx/sites-available/{{ domain_name }}.conf"
    regexp: "^(.*)ssl_certificate_key {{ letsencrypt_dir }}"
    line: "\tssl_certificate_key {{ letsencrypt_keys_dir }}/{{ domain_name }}.key;"